### ISSUE TITLE
Please add an "ignore_files" attribute 

### ISSUE THREAD

**Issue by AzySir** [terraform-providers/terraform-provider-archive#60]
**Feature Request:** Are we able to add an "ignore_files" parameter so that we can ensure we aren't zipping everything inside of a folder. I know the simple solution is zip into a different folder however this then just adds another folder unnecessarily feels a little dirty.

**Comment by manasouza** [comment]
Actually there's an `excludes` attribute that can be used. It's mentioned in [changelog](https://github.com/terraform-providers/terraform-provider-archive/blob/8b74ce13474aecc5cb753350b7f997453380d541/CHANGELOG.md#110-july-30-2018)

I recently added an attempt to enhance this functionality: https://github.com/terraform-providers/terraform-provider-archive/pull/57

**Comment by AzySir** [comment]
@manasouza thanks so much for that !!! I have a question would this work if I did something like 

```
excludes: [ "*.zip" ] 
``` 

Would that work, to exclude file type?

**Comment by AzySir** [comment]
#61 I've referenced a PR for added documentation for "excludes" functionality

**Comment by manasouza** [comment]
> @manasouza thanks so much for that !!! I have a question would this work if I did something like
> 
> ```
> excludes: [ "*.zip" ] 
> ```
> 
> Would that work, to exclude file type?

Yes @AzySir, that should work

**Comment by AzySir** [comment]
Great news - I'm closing this issue as the functionality did already exist however the documentation has not been updated on the terraform provider docs. That has been added under #61 and is awaiting a code review and an approval for Pull Request.
