### ISSUE TITLE
Archive Strips File Attributes

### ISSUE THREAD

**Issue by dthagard** [terraform-providers/terraform-provider-archive#8]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
- data.archive_file

### Terraform Configuration Files
```hcl
resource "local_file" "env" {
  content  = "{\"APEX_FUNCTION_NAME\":\"${var.function_name}\",\"LAMBDA_FUNCTION_NAME\":\"${var.project_name}_${var.function_name}\"}"
  filename = "${path.module}/dist/.env.json"
}

resource "null_resource" "build_lambda" {
  provisioner "local-exec" {
    command = <<EOF
mkdir -p ${path.module}/dist
CGO_ENABLED=0 GOOS=linux GOARCH=amd64 go build -ldflags -f -a -o ${path.module}/dist/main ${path.module}/src/main.go
chmod +x ${path.module}/dist/main
cp ${path.module}/src/*.js ${path.module}/dist
EOF
  }

  triggers {
   sha = "${base64sha256(file("${path.module}/src/main.go"))}"
  }

  depends_on = ["local_file.env"]
}

data "archive_file" "lambda_zip" {
  type        = "zip"
  source_dir  = "${path.module}/dist"
  output_path = "${var.build_path}"
  depends_on  = ["null_resource.build_lambda"]
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The archive should include the golang binary with the executable flag set.

### Actual Behavior
All of the file attributes were stripped from the binary.

### Steps to Reproduce
1. Create a file with +x attr
2. Use the `data.archive_file` resource to archive the file from step 1.
3. Run `terraform apply`
4. Inspect the archive file. File is stripped of the +x attribute.

### Important Factoids
The zip archiver is using the https://golang.org/pkg/archive/zip/#Writer.Create method which does not preserve the file header info. The https://golang.org/pkg/archive/zip/#Writer.CreateHeader method should be used instead to preserve the attributes of the files within the archive.

The executable attribute is critical when using NodeJS as a shim to execute golang binaries in AWS Lambda. Without the +x flag set, the Lambda is not able to invoke the binary correctly from the uploaded archive.

### References
 - None

**Comment by paultyng** [comment]
The fix to this is included in v1.0.1 and was released earlier today.
